### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by bearded-avenger** [WordPressDemo/WP-Demo#11]
Hey guys,
I'm unable to get this to function on mobile (iOS). The loader just spins and doesn't do anything at all.

**Comment by bearded-avenger** [comment]
Just a friendly bump on this. Is this the proper method of support for this plugin?

**Comment by dovy** [comment]
Sorry about the delay. My twin boys were born July 30th. 2 weeks prior to that my wife went into labor and they had to stop it (so i was daddy-mommy).

Since their birth my twins were in the NICU, so my wife was at the hospital for 3 weeks, and I was there 10 days of that. This week one of my sons went into the hospital again and I was up for 30 hours yesterday holding my screaming son. I've been a little crazier than I've ever been. Sorry.

Yes, it is not working yet on Mobile. I could probably make that happen pretty quickly. I am sorry for the delay. Stay posted, I'll try to get this done this next week.

**Comment by bearded-avenger** [comment]
Dovy,
Thanks for the reply, really sorry to hear about your boys, will say a few prayers.

Re: the bug, it's not so bad if it can't run on mobile, but the site should at least be accessible.

**Comment by dovy** [comment]
Just tried with 1.0.5. Seems to work fine. Can you verify?

**Comment by dovy** [comment]
Seems fine here. Reopen if it's still a problem.

**Comment by bearded-avenger** [comment]
http://aesopthemes.com/jorgen

does this work for you guys on mobile? I've yet to get wpdemo.io to function on mobile
