### ISSUE TITLE
Question about Custom Integration

### ISSUE THREAD

**Issue by approveme** [WordPressDemo/WP-Demo#21]
Hey Guys thanks for this awesome plugin!

We currently have our main site hosted on one multi-site installation and the WP Demo hosted on a completely different multi-site server installation.

For security reasons (and speed) we would like to keep these installations separate yet still trigger a popup that collects the Email and send the WP Demo link when a user on the main site clicks "Try Free Demo".

What is the best method/way to go about this?

Thanks!

Kevin
kevin.gray@rockstaridea.com

**Comment by dovy** [comment]
That would be tough since it's cross-site. You could maybe do an iframe.

Here's what we do:
http://redux.wpdemo.io/wp-admin/admin-ajax.php

Post this data:
    action:wpdemo_popup
    parent_blog_id:1
    submit_label:Launch Demo

It MAY pop-up the window, but because of cross-domain it may not be able to redirect.

Best bet would be to launch to the new site and maybe have JS auto-click on the launch demo button. That would ensure that it works.
