### ISSUE TITLE
Can't activate 1.0.3

### ISSUE THREAD

**Issue by seedprod** [WordPressDemo/WP-Demo#7]
When I try to activate I get a message that says, "Are you sure you want to do this? Please try again."  and it just loops when I try again.

**Comment by dovy** [comment]
Sorry about the delay. My twin boys were born July 30th. 2 weeks prior to that my wife went into labor and they had to stop it (so i was daddy-mommy).

Since their birth my twins were in the NICU, so my wife was at the hospital for 3 weeks, and I was there 10 days of that. This week one of my sons went into the hospital again and I was up for 30 hours yesterday holding my screaming son. I've been a little crazier than I've ever been. Sorry.

Can you get me server access? I can try and debug. dovy@reduxframework.com.

Thanks!

**Comment by seedprod** [comment]
No worries, I just deleted it and reinstalled. Hope things get better for you and your family soon!
